stages:
  - build
  - test

build:
  image: kasproject/kas:2.0
  stage: build
  tags:
    - local
    - build
  timeout: 6h
  cache: {}
  script:
    - cd ..
    - sed -e "s@<YOCTO_HTTP_CACHE_IP>@$YOCTO_HTTP_CACHE_IP@" -i meta-trenchboot/kas-cache.yml
    - kas build meta-trenchboot/kas-pcetb-base.yml:meta-trenchboot/kas-cache.yml
    - kas build meta-trenchboot/kas-pcetb-xen.yml:meta-trenchboot/kas-cache.yml
  after_script:
    - mkdir artifacts
    - echo "https://gitlab.com/trenchboot1/3mdeb/meta-trenchboot/-/jobs/$CI_JOB_ID/artifacts/download" > artifacts/artifacts_url.txt
    - cp ../build/tmp/deploy/images/pcengines-apu2/tb-minimal-image-pcengines-apu2.wic.gz artifacts
    - cp ../build/tmp/deploy/images/pcengines-apu2/xen-tb-dom0-image-pcengines-apu2.wic.gz artifacts
    - cp ../build/tmp/deploy/images/pcengines-apu2/tb-minimal-image-pcengines-apu2.wic.bmap artifacts
    - cp ../build/tmp/deploy/images/pcengines-apu2/xen-tb-dom0-image-pcengines-apu2.wic.bmap artifacts
    - time rsync -av -e "ssh -i $YOCTO_HTTP_CACHE_RSYNC_KEY -o StrictHostKeyChecking=no" ../build/downloads $YOCTO_HTTP_CACHE_USER@$YOCTO_HTTP_CACHE_IP:$YOCTO_CACHE_PATH
    - time rsync -av -e "ssh -i $YOCTO_HTTP_CACHE_RSYNC_KEY -o StrictHostKeyChecking=no" ../build/sstate-cache $YOCTO_HTTP_CACHE_USER@$YOCTO_HTTP_CACHE_IP:$YOCTO_CACHE_PATH
  artifacts:
    name: "meta-trenchboot-${CI_COMMIT_SHA::12}"
    paths:
      - artifacts/*

test_boot_apu2:
  image:
    name: 3mdeb/rf-docker:0.4.2
    # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image
    # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2692
    # use EMPTY ENTRYPOINT for docker >17.06
    entrypoint: [""]
  stage: test
  tags:
    - local
    - test
  cache: {}
  before_script:
    - git clone https://github.com/3mdeb/testing-trenchboot
    - cd testing-trenchboot
    - git show HEAD
    - git submodule sync
    - git submodule update --init
  script:
    - export ARTIFACTS_URL=$(cat ../artifacts/artifacts_url.txt)
    - robot -L TRACE -v rte_ip:$RTE_IP_APU2 -v config:apu2 -v artifacts_link:$ARTIFACTS_URL os/yocto_install.robot
  artifacts:
    paths:
      - testing-trenchboot/log.html
      - testing-trenchboot/report.html
      - testing-trenchboot/output.xml
    when: always
