stages:
  - build

build:
  image: kasproject/kas:2.0
  stage: build
  tags:
    - local
    - build
  timeout: 6h
  cache: {}
  script:
    - cd ..
    - kas build meta-trenchboot/kas-pcetb-initramfs.yml
    - kas build meta-trenchboot/kas-pcetb-base.yml
    - kas build meta-trenchboot/kas-pcetb-xen.yml
  after_script:
    - mkdir artifacts
    - cp ../build/tmp/deploy/images/pcengines-apu2/tb-minimal-image-pcengines-apu2.wic.gz artifacts
    - cp ../build/tmp/deploy/images/pcengines-apu2/xen-tb-dom0-image-pcengines-apu2.wic.gz artifacts
    - cp ../build/tmp/deploy/images/pcengines-apu2/tb-minimal-image-pcengines-apu2.wic.bmap artifacts
    - cp ../build/tmp/deploy/images/pcengines-apu2/xen-tb-dom0-image-pcengines-apu2.wic.bmap artifacts
    - cp ../build/tmp/deploy/images/pcengines-apu2/tb-minimal-initramfs-image-pcengines-apu2.cpio.gz artifacts
    - time rsync -av -e "ssh -i $YOCTO_HTTP_CACHE_RSYNC_KEY -o StrictHostKeyChecking=no" ../build/downloads $YOCTO_HTTP_CACHE_USER@$YOCTO_HTTP_CACHE_IP:$YOCTO_CACHE_PATH
    - time rsync -av -e "ssh -i $YOCTO_HTTP_CACHE_RSYNC_KEY -o StrictHostKeyChecking=no" ../build/sstate-cache $YOCTO_HTTP_CACHE_USER@$YOCTO_HTTP_CACHE_IP:$YOCTO_CACHE_PATH
  artifacts:
    name: "meta-trenchboot-${CI_COMMIT_SHA::12}"
    paths:
      - artifacts/*
