require conf/distro/include/tb-distro-common.conf

DISTRO = "tb-xen-distro"
DISTRO_FEATURES += "virtualization xen"

IMAGE_INSTALL += " xen xen-tools"

IMAGE_EFI_BOOT_FILES += " \
    xen-${MACHINE}.gz;xen.gz \
"
